### ISSUE TITLE
Не работает на Windows

### ISSUE THREAD

**Issue by StbEx** [artyl/mbplugin#22]
Интересует stanalone версия.
Не запускается ни на серверной версии ни на Windows 10.

Не нашел системных требований - на какой системе программа заработает точно?

При запуске standalone/mbp.dat:
На Windows 10 говорит что mbplugin/python/python не является программой или исполняемым файлом. При этом в папке python исчезают почти все файлы.

На Windows Server 2019  идет но в конце ошибка:

...
OK check-import
Fail check-ini mbplugin.ini
Section [Options]: Error logginghttpfilename="C:\Users\Administrator\Desktop\mbplugin\log\http.log", invalid (not check validation)
Section [Options]: Error balance_html="C:\Users\Administrator\Desktop\balance.html", invalid (not check validation)
OK check-ini phones.ini
OK clear_browser_cache
...
Traceback (most recent call last):
  File "mbplugin\plugin\util.py", line 867, in <module>
    cli(obj={})
  File "C:\Users\Administrator\Desktop\mbplugin\python\lib\site-packages\click\core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Administrator\Desktop\mbplugin\python\lib\site-packages\click\core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "C:\Users\Administrator\Desktop\mbplugin\python\lib\site-packages\click\core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\Administrator\Desktop\mbplugin\python\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Administrator\Desktop\mbplugin\python\lib\site-packages\click\core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\Administrator\Desktop\mbplugin\python\lib\site-packages\click\decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "mbplugin\plugin\util.py", line 663, in version
    echo(f'New version found {version}\n{msg_version}')
  File "mbplugin\plugin\util.py", line 35, in echo
    f.write(f"{time.strftime('%d.%m.%Y %H:%M:%S', time.localtime())} {msg}\n")
  File "encodings\cp1252.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode characters in position 147-156: character maps to <undefined>

**Как мне заставить программу работать?**

**Comment by artyl** [comment]
На windows 10 все прекрасно работает.
Подозреваю что вы скачали mbplugin_bare.v1.00.20.zip вместо mbplugin.v1.00.20.zip
Также замечу, плохая идея распаковыкать непосредственно в C:\Users\Administrator\Desktop\
Создайте где-нибудь на диске например c:\mbstandalone и распакуйте содержимое правильного архива туда.
А на windows server 2019 подозреваю что у вас не до конца установлен русский язык раз он ругается на cp1252.

**Comment by StbEx** [comment]
В этих ваших названиях и папках я конкретно запутался, хотя я линукс и виндовс администратор много лет. Я просто хочу запустить - неважно в какой среде данную программу. На сегодняшний день мне это не удалось, хотя потратил пол вечера, и на винде и не только. Мои серверы работают под cPanel где нужно танцевать с бубном для Python 3, вероятно в этом дело. Но и на винде тоже не пошло. Могу создать ВМ с Ubuntu и установить там все с нуля, чтобы добиться того, чтобы скрипт работал. Мой идеал это скрипт на PHP который можно запустить везде, или Curl. Задача - смотреть баланс ТЕЛЕ2 акков.

**Comment by StbEx** [comment]
Есть среда Yandex Cloud VM - Windows Server 2019, но не получается там настроить. Почему-то даже от названия корневой папки получается разный результат, вы можете мне немного помочь это настроить как автор программы?

**Comment by artyl** [comment]
Попробуйте еще раз установить с нуля по инструкции. 
Про win 2019 не знаю не проверял, у меня нет, допускаю могут быть какие-то нюансы.
Но на win10 работает у меня и еще у кучи людей. На linux у меня тоже работает, есть еще пользователи запускающие на linux.
Можно запускать из консоли через mbp check-plugin, 
также есть проект https://github.com/svetlyak40wt/mobile-balance для консоли он я думаю вам больше подойдет
Посмотрите логи, логи подробные в них много информации есть. 
Есть исходники их тоже при желании можно посмотреть.
Не работает это не описание ситуации - правильное описание ситуации это:
Я делаю .... - получаю ....
Раз не работает, значит Вы сделали что-то не так, но без подробного описания я не могу понять в чем дело.

**Comment by StbEx** [comment]
Попробую еще варианты, благодарю за ваши советы.

**Comment by artyl** [comment]
Если появится дополнительная информация - переоткройте тикет или заведите новый
