### ISSUE TITLE
символ % в пароле вызывает ошибку

### ISSUE THREAD

**Issue by volgamax** [artyl/mbplugin#23]
File "configparser.py", line 799, in get
  File "configparser.py", line 395, in before_get
  File "configparser.py", line 442, in _interpolate_some
configparser.InterpolationSyntaxError: '%' must be followed by '%' or '(', found: '%sXg8'

**Comment by artyl** [comment]
Спасибо за замечание, сколько пользуюсь configparser а даже не знал что он по умолчанию так себя ведет.

**Comment by artyl** [comment]
Исправлено в [5589b78](https://github.com/artyl/mbplugin/commit/5589b78f0757e3b854042f211fbd2bba3964b866)
Войдет в релиз v1.00.28

**Comment by volgamax** [comment]
А подскажите, с МТС вообще работает? у меня не получилось баланс получить, там капча при логине.
Есть ли в планах баланс корп.номеров со страницы https://lk-b2b.mts.ru ? Ооочень нужно :) (там без капчи)

**Comment by artyl** [comment]
Исправления вошли в релиз [v1.00.28](https://github.com/artyl/mbplugin/releases/tag/v1.00.28)
Этот issue вроде как не по поводу МТС открыт, не надо все в одну кучу мешать.
В целом обсуждение идет в канале телеграм, а здесь формализовано есть проблема открывайте issue или pull request.
По МТС действительно есть проблемы - открыл issue [24](https://github.com/artyl/mbplugin/issues/24)
Что касается корпоративного МТС - если баланс можно через браузер получить, то 99% можно и плагин написать, нужно только время.
Найдется хотя бы несколько человек - можно будет уделить время. Но в приоритете основные операторы.
