### ISSUE TITLE
Проблемы с получением балансов МТС.

### ISSUE THREAD

**Issue by artyl** [artyl/mbplugin#24]
С 5.07.22. появились проблемы при получении балансов телефонов МТС

**Comment by solistos** [comment]
Приветствую!
пароли без странных символов ***1Q2w**** (цифры и буквы)
и вдруг перестал забирать баланс МТС  с 00ч00м 06 июля 2022

перечень плагинов
[2022-07-07-22-57-10-Mobile-Balance-18-03-08-05-2018.jpg](https://postimg.cc/t10bpyJT)

mts.py и mts2.py. (*.dll)
Прошу помощи

**Comment by artyl** [comment]
Исправлено в v1.00.28
