### ISSUE TITLE
Не работает проверка балансов МТС в mbplugin под Linux

### ISSUE THREAD

**Issue by yoman88111** [artyl/mbplugin#28]
Не работает проверка балансов МТС в mbplugin под Linux
В скриншотах либо пустой экран либо только окно логина.

В логе это:
INFO wait_params Wait Balance
ERROR wait_params Not found all param on : Balance,#banner1
INFO wait_params Wait TarifPlan, Balance, Balance2, #counters, UserName
ERROR wait_params Not found all param on : TarifPlan,Balance,Balance2,#counters,UserName
INFO page_goto goto timeout
INFO getbalance_plugin mts fail: Traceback (most recent call last):
  File "/mbstandalone/mbplugin/plugin/httpserver_mobile.py", line 201, in getbalance_plugin
    raise RuntimeError(f'В result отсутствует баланс')
RuntimeError: В result отсутствует баланс

**Comment by artyl** [comment]
Только что попробовал, у меня МТС работает в Linux. 
Версия точно последняя?
Попробуйте в отдельной папке поставить с нуля и проверить.

**Comment by artyl** [comment]
Закрываю по неактивности. Если вернетесь с подробностями откроем заново.

**Comment by yoman88111** [comment]
> Только что попробовал, у меня МТС работает в Linux. Версия точно последняя? Попробуйте в отдельной папке поставить с нуля и проверить.

Пробовал поставить с нуля в отдельную папку. Результат тот же. Сначала из 40 номеров проверял только около 7. При чем одних и тех же. Попытался понять есть ли разница в ЛК, но никакой взаимосвязи не выявил. Сейчас не проверяет вообще. 
Еще один нюанс, проверка идет через http proxy.

**Comment by artyl** [comment]
Фиг знает. У МТС античит на странице работает, но если обход защиты не проходит, то окно логона просто не открывается. Вместо формы пароля сообщение:
403 Error Forbidden Доступ к сайту login.mts.ru запрещен.
Раз на части номеров работает, то значит дело не в линуксе, а в этих номерах.
Попробуйте без прокси, попробуйте на машине с виндой. Может выяснятся какие-то закономерности.
Смотрите скриншоты, смотрите лог может там что-то будет.

**Comment by yoman88111** [comment]
По логу не понятно. На скриншотах либо белый экран, либо окно логина постоянно.

**Comment by artyl** [comment]
Закрываю по неактивности. Если вернетесь с подробностями откроем заново.
