### ISSUE TITLE
Отображение истории балансов во всплывающем окне

### ISSUE THREAD

**Issue by pasha00000** [artyl/mbplugin#32]
С добавлением !DOCTYPE html> в table_template (406 строка) в файл settings.py в версии v1.00.46 заметил 2 момента на странице http://localhost:19777/report

1. При наведении на баланс появляется всплывающее окно, в котором весь текст стал жирным - ранее жирным выделялся только баланс. При этом со столбцом "услуги" всё ок - жирным выделена только сумма.

Наглядно:
Без !DOCTYPE html> (до версии 1.00.46)
![2022-12-31_001305](https://user-images.githubusercontent.com/43064642/210112470-c6c95e6b-b0f1-4c48-a192-504f197825aa.png)

С !DOCTYPE html> (начиная с версии 1.00.46)
![2022-12-31_001342](https://user-images.githubusercontent.com/43064642/210112455-3012ad78-abc0-4970-9313-ff2912797fb2.png)

2. Общий вид страницы немного меняется:
- Нумерация в NN, заголовки "Номер" и "Тариф. план" выровнялись по правому краю вместо центра
- Если таблица не влезала в экран - некоторые столбцы сужались (на скрине это "Delta (день)", "Delta (запрос)" и "Дней без изм."), теперь таблица просто вылезает за границы экрана

Наглядно:
Без !DOCTYPE html> (до версии 1.00.46)
![2022-12-31_001525](https://user-images.githubusercontent.com/43064642/210112610-f3e7f263-3223-4b79-ac93-98f1a7b09846.png)

С !DOCTYPE html> (начиная с версии 1.00.46)
![2022-12-31_001530](https://user-images.githubusercontent.com/43064642/210112612-2aa0f6ad-5053-4d73-9ca9-8abfde0883e1.png)

Так было задумано или это баг?

**Comment by artyl** [comment]
Вот черт, даже не заметил, спасибо. 
Решал другую проблему, в процессе оставил, полагая что это ни на что не влияет.
Оказывается их там куча разных вариантов, но при наличии DOCTYPE при любом он показывает по другому.
Я надеюсь что разборки с этим не заняли у Вас много времени.
Уберу в следующем релизе.

**Comment by pasha00000** [comment]
Спасибо)

**Comment by artyl** [comment]
Исправил в релизе [v1.00.48](https://github.com/artyl/mbplugin/releases/tag/v1.00.48)
