### ISSUE TITLE
Группы

### ISSUE THREAD

**Issue by ReMGT** [artyl/mbplugin#33]
Было бы супер добавить в **Mbplugin** группы + разный цвет
Иногда нужно контролировать большое количество симок
и они для разных целей

В софтине **_MobileBalance_** раньше была такая возможность

Как я думаю это можно реализовать с наименьшими танцами
у нас есть phones.ini файлик в котором номера и вся нужная инфа для них
что если - эти файлы и сделать - группы
phones.ini
1phones.ini
2phones.ini

в начале каждого файла (phones.ini) добавить параметры
[Group] - Группа номер 1
[Color] - #66555

а вывод сделать друг под другом - ерархия название файла
phones.ini
1phones.ini
2phones.ini

Единственно в колонке появиться - Группа
и при превышении скажем 50 строк в группе - сделать аккордеон - (+)
Или вообще сделать разные отчёты - типа много поток

**Comment by artyl** [comment]
Родился вот такой вариант (в отличии от описанного вами довольно прост в реализации)
В `phones.ini` размечаем группы, поле `Indication = Work`
И на основной странице будут ссылки на отчеты по конкретным группам
![изображение](https://user-images.githubusercontent.com/3335860/215190362-84b6d011-e319-4460-95ba-54ef69b57601.png)
Т.е. при клике на View report видим список из всех телефонов, 
![изображение](https://user-images.githubusercontent.com/3335860/215191419-a7fb6baf-c660-4ea6-a6f6-1e5f036216e5.png)
а при клике на группу - только по телефонам этой группы.
![изображение](https://user-images.githubusercontent.com/3335860/215191554-8180d4f9-cfcf-4947-8de8-7dcfeebffee7.png)

**Comment by ReMGT** [comment]
ну супер )
я просто первую мысль накинул )

я просто не программер , а креативщик (генератор)
щас ищу программера для бота на ТГ

**Comment by artyl** [comment]
Ну и славно. Тогда закрываю в таком виде.
[Реализовано в релизе v1.00.49](https://github.com/artyl/mbplugin/releases/tag/v1.00.49)
