### ISSUE TITLE
Конвертер csv -> phones.ini

### ISSUE THREAD

**Issue by ReMGT** [artyl/mbplugin#36]
[Phone] #1
Indication = Work1
Region               = p_mts2
**Monitor              = TRUE**
Alias                = 79111111111
Number               = 79111111111
**BalanceNotChangedMoreThen = 60
BalanceChangedLessThen=1
BalanceLessThen=100
TurnOffLessThen=1**
Password2 = pass111111111

Пример CSV
Number;Alias;Password2;Indication

79111111111;79111111111;pass111111111;Work1

то что выделено **жирным** - это не меняется

**Comment by ReMGT** [comment]
[Phone] #1
Indication = Work1
Region               = p_mts2
Monitor              = TRUE
Alias                = 79111111111
Number               = 79111111111
BalanceNotChangedMoreThen = 60
BalanceChangedLessThen=1
BalanceLessThen=100
TurnOffLessThen=1
Password2 = pass111111111

[Phone] #2
Indication = Work1
Region               = p_mts2
Monitor              = TRUE
Alias                = Ivanych
Number               = 7922222222
BalanceNotChangedMoreThen = 60
BalanceChangedLessThen=1
BalanceLessThen=100
TurnOffLessThen=1
Password2 = pass22222222

[Phone] #3
Indication = Work1
Region               = p_mts2
Monitor              = TRUE
Alias                = Lilli
Number               = 7933333333
BalanceNotChangedMoreThen = 60
BalanceChangedLessThen=1
BalanceLessThen=100
TurnOffLessThen=1
Password2 = pass33333333

[Phone] #4
Region               = p_mts2
Monitor              = TRUE
Alias                = НВ
Number               = 7944444444
BalanceNotChangedMoreThen = 60
BalanceChangedLessThen=1
BalanceLessThen=100
TurnOffLessThen=1
Password2 = pass4444444

[Phone] #5
Region               = p_mts2
Monitor              = TRUE
Alias                = ОлькА
Number               = 7955555555
BalanceNotChangedMoreThen = 60
BalanceChangedLessThen=1
BalanceLessThen=100
TurnOffLessThen=1
Password2 = pass555555555

**Comment by artyl** [comment]
Решил сделать более универсальный вариант.
В файле phones.csv находятся все поля которые должны попасть в phones.ini разделенные табуляцией (если хотите другой символ его можно поменять в первой строчке файла скрипта csv_to_phones_ini.py)
В архиве скрипт и пример CSV файла
[csv_to_phones_ini.zip](https://github.com/artyl/mbplugin/files/11082583/csv_to_phones_ini.zip)
Первая строчка phones.csv  это заголовки (то что в ini будет перед равно) строчки начиная со второй - значения
кладете в одну папку файл csv_to_phones_ini.py из архива и подготовленный csv файл.
Запускаете (исправьте на путь к Вашему python)
`C:\mbstandalone\mbplugin\python\python.exe csv_to_phones_ini.py `
После запуска будет создан файл phones.gen.ini проверяете, если все ок - переименовываете и кладете вместо phones.ini
Задача разовая, так что не уверен что стоит это добавлять в код mbplugin как опцию пока оставим в таком сыром виде.
Возможно потом сделаю в более удобоваримом виде.

**Comment by artyl** [comment]
[Add in v1.00.59](https://github.com/artyl/mbplugin/releases/tag/v1.00.59)
