### ISSUE TITLE
В плагине mts не работает работа через прокси

### ISSUE THREAD

**Issue by yoman88111** [artyl/mbplugin#38]
При запуске Chrome  в 121 строке плагина mts.py не передаются параметры запуска chrome. 
Туда следует добавить строку с прокси, если он указан в конфигк
f'--proxy-server=http://IP:port'

Кроме этого, при работе из-под Linux в mts.py неправильно указан путь к браузеру:
elif sys.platform == 'linux':
                pbp = os.environ.get('PLAYWRIGHT_BROWSERS_PATH', os.path.join(pathlib.Path.home(), '.cache', 'ms-playwright'))
                self.browser_path = os.path.join(pbp, f'chromium-{revision}', 'chrome-win', 'chrome')
вместо chrome-win должно быть chome-linux

**Comment by yoman88111** [comment]
Так же из того, что я заметил, если в Windows прописан прокси, то mbplugin просто открывает браузер и не запускает никакой проверки баланса. Количество открытых окон в конце равно количеству номеров для проверки. (проверялось на МТС)

**Comment by artyl** [comment]
Извиняюсь за долгий ответ, спасибо за Ваши комментарии.
Да про прокси в процессе битвы с CDP потерялось, займусь. 
Касательно chrome-linux тоже спасибо, исправлю, интересно что у всех кто в опросе поставил галку напротив линукса нет МТС.
Интересно а в Mac OS там chome-linux или как-то по другому ? Сейчас там chome-win что точно неправильно, но правда за MacOS голосов вообще не было.

**Comment by artyl** [comment]
[Fix in v1.00.59](https://github.com/artyl/mbplugin/releases/tag/v1.00.59)
