### ISSUE TITLE
Пакеты интернета МТС

### ISSUE THREAD

**Issue by Gl0** [artyl/mbplugin#39]
[вот тут](https://github.com/artyl/mbplugin/blob/master/plugin/mts.py#L490) стоит отсортировать по полю priority в обратном порядке, чтобы при наличии турбокнопки и базового 20МБ ежедневного пакета показывался остаток турбокнопки а не вечные 20МБ.

**Comment by artyl** [comment]
У меня никогда больше одного не было, а вот вопрос как быть с packageGroup (я правда уже не помню осознанно я добавил не Main или на всякий случай).
Наверное правильно сортировать все в пределах packageGroup=Main а потом добавлять то что не Main.
Попробуйте поставить перед  строкой 487 `if internet != []:`  вот такую строчку
`internet.sort(key=lambda el: (el.get('packageGroup') == 'Main', el.get('priority', 0)), reverse=True)`
Если это решит Вашу проблему добавлю в следующем релизе.

**Comment by Gl0** [comment]
У меня других packageGroup нет, поэтому для себя я просто добавил `internet.sort(key=lambda x: x['priority'], reverse=True)`

**Comment by Gl0** [comment]
Возможно сортировку по packageGroup добавили в попытке получить тот же эффект что и от сортировки по priority.

**Comment by artyl** [comment]
У меня никогда больше одного не было, а вот вопрос как быть с packageGroup (я правда уже не помню осознанно я добавил не Main или на всякий случай).
Наверное правильно сортировать все в пределах packageGroup=Main а потом добавлять то что не Main.
Попробуйте поставить перед  строкой 487 `if internet != []:`  вот такую строчку
`internet.sort(key=lambda el: (el.get('packageGroup') == 'Main', el.get('priority', 0)), reverse=True)`
Если это решит Вашу проблему добавлю в следующем релизе.

**Comment by artyl** [comment]
Несколько packageGroup у меня то как раз и есть, я просто не до конца уверен что все кроме Main можно выкидывать, возможно есть какие-то сценарии в которых они полезны.
Ваш вариант я не могу использовать, т.к. и меня при сортировке только по приоритету вылезает как раз эта другая packageGroup.
Так что для того чтобы ни у кого не ломалось нужен вариант который будет оба поля учитывать как я написал или какой-то еще но не ваш.

**Comment by Gl0** [comment]
поменял на `internet.sort(key=lambda el: (el.get('packageGroup') == 'Main', el.get('priority', 0)), reverse=True)`
отрабатывает нормально

**Comment by artyl** [comment]
Ок, добавил этот [d33b327](https://github.com/artyl/mbplugin/commit/d33b32779c46e4286958a5d50fd1ccffcac376da) будет в следующем релизе.
